name: CI

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nwisbeta/validate-yaml-schema@v2.0.0
        with:
          yamlSchemasJson: |
            {
                "nft_schema.json": "nfts/*"
            }
